### ISSUE TITLE
Social Activity Counter Behavior

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#111]
The social activity feed (2-person icon) should have a blue dot whenever there is new content in the You or Following tabs. However, after opening the feed, that blue dot should immediately disappear regardless of the counters. Similarly, after opening the Following tab, its counter should immediately disappear. The You tab's counter should only reflect the number of follow requests that have not been Ignored.

General background:
The newsfeed (3-person icon) and the social activity feed (2-person icon) are two different levels of importance. The newsfeed counters are all red. Every tile in the Group Selector that should have a counter should be red. Every item in the newsfeed that is part of the count should have a red dot. This is intended to prioritize attention and response to those items. The red counters only go down when action has been taken... On the other hand, the blue counters aren't as important in the social activity feed. We want to bring their attention to it, but we don't need them to take action on these items as much as the red items. This is why it's "easier" to make the blue counters disappear and harder to make the red counters disappear... We want the red counters to kind of annoy people - like a voicemail icon annoys you to call your voicemail and delete your messages so that the icon disappears :-)

**Comment by petervojtek** [comment]
@jterps08 , I altered the counter behaviour so that:
- Once you visit a social feed, the blue counter new 2-person icon disapears
- Once you visit the social feed - Following, the counter new Following title disapears

The "hide" behaviour applies only is context of current session. This means,
when you reload the app (in browser by F5, in smartphone by closing the app and turning it on again), the counters will be visible again until you visit the appropriate screen. We can do these changes more permanent if needed, but that will be more time consuming.

Regarding "The You tab's counter should only reflect the number of follow requests that have not been Ignored.", I created separate issue #120

Regarding "Every tile in the Group Selector that should have a counter should be red. Every item in the newsfeed that is part of the count should have a red dot. ", I created issue @121
