### ISSUE TITLE
Social feed: The You tab's counter should only reflect the number of follow requests that have not been Ignored.

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#120]
currently it counts every request, disregarding if it is ignored or not.

**Comment by petervojtek** [comment]
@jterps08 , does it makes sense to both Ignore and Follow the same person? Currently it is possible.

**Comment by jterps08** [comment]
@petervojtek - thanks for this question. Yes, it's possible to want to ignore someone's request to follow you, but still want to try to follow them (and vice versa)... The thinking is this: Followers/Followed Users on Powerline are really very different from Twitter, for example, because of the type of data sent to an approved follower. Each one of your followers is notified with a push notification alert each time you create a new post in the same group. They can see how you answered a poll via Social Influences on a poll. They can see each time you've commented on something. The entire "Following" tab is populated based on the people you follow - depending on the circumstances, someone might not want to allow a co-worker to follow them, for example.

**Comment by jterps08** [comment]
@petervojtek - thanks for this question. Yes, it's possible to ignore someone's request to follow you, but still want to try to follow them (and vice versa)... The thinking is this: Followers/Followed Users on Powerline are really very different from Twitter, for example. Each one of your followers is notified with a push notification alert when you create a new post in the same group. They can see what you commented on and how you answered a poll. So, you may not want to allow your co-worker to see you, but your co-worker may allow you to see them, etc.
