### ISSUE TITLE
Newsfeed: comment counter is zero disregarding the actual number of comments

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#127]

**Comment by petervojtek** [comment]
@jterps08 , in newsfeed next to each activity is a counter which currently displays attribute  `responses_count` as is provided by backend API. 
Based on my experiments, the counter corresponds to number of votes (see screenshot). The counter is not taking into account number of comments of a Post. I am not sure if it is intended behaviour that it ignores comments, or not.

<img width="717" alt="screen shot 2016-07-04 at 14 35 52" src="https://cloud.githubusercontent.com/assets/225506/16560639/f54b6f22-41f4-11e6-9794-5578b8685e99.png">

**Comment by jterps08** [comment]
Let's come back to the comment counter issue later... Thanks!

**Comment by jterps08** [comment]
**FYI:** the intended behavior is to count comments.

**Some additional somewhat unrelated notes for future reference:**

At some point in the future, we may need an indicator that displays the current number of votes. We need to somehow indicate engagement with the post (e.g. comments + votes). We would not want people to see the number of votes until they voted themselves, but we would want to somehow show that people are voting on the post. 

The "boosting" concept algorithm will likely need to be changed from a basic percentage to something that is a bit more complex. The boosting algorithm will have to account for how many posts have been boosted in the last 2 days and the last few hours, but it will also need to account for how many other posts in the group are "near" the boosting level... Basically, we need it to be "harder" to boost a post when many posts are getting boosted automatically by the system in a short time. It's okay if many posts get boosted, we just want to make sure that we don't go overboard... I mention all of this because a counter that shows the number of votes on the post could be used by a smart user to  'find' all of the posts that are near boosting level and quickly boost all of them, and we would want to discourage that kind of behavior. We may also want to consider this: If a user's vote is going to be the deciding factor for whether or not the post gets boosted, we may want to give the user the ability to either boost or require one more vote to get boosted. This would help manage the noise, too...

**Comment by petervojtek** [comment]
@igaponov , in activity newsfeed we want to display number of comments. However currently there does not seems to any attribute in activity which exhibits this number.

For example, here is activity for micro-petition:quorum (which has 1 comment):

```
{"id":459,"title":"","description":"trying www.google.com link thumbnail","sent_at":"2016-07-27T07:02:53.000Z","expire_at":"2016-07-28T07:02:53.000Z","responses_count":0,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Peter10","avatar_file_path":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg"},"entity":{"type":"micro-petition:quorum","id":227,"group_id":296},"picture":null,"read":true,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-07-27T07:02:53+0000","metadata":{"title":"Google","description":"Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for.","image":null},"quorum":0,"owner_info_1":null}
```

there is an attribute `responses_count`, but it's value is zero.

**Comment by jterps08** [comment]
FYI: There's responses_count (which is the number of upvotes + downvotes I believe) and there's comments count. We need comments count.

Peter - One UI idea for displaying responses count in future is including that number in a little "P" icon (powerline P) as 3 upvotes and 5 downvotes  as "-2" for example. Instead of actually stating 3 up, 5 down. Rationale: We don't want people to necessarily change their upvote/downvote behavior based on whether or not something is near boosting level - a smart user could figure out that the boosting level in that specific group is 9 and would purposely engage with the post (up or down) just to boost it. the differential score (-2 in this example) would encourage engagement without providing the wrong incentive.... Open to thoughts, def a low-priority enhancement that I can open as a separate issue.

**Comment by igaponov** [comment]
@petervojtek @jterps08 currently `responses_count` is the comments count on petition creation or petition update, because activity is created on petition create/update event (if somebody add comment this number will not change). So, do we need to expose real `comments_count` or not?

**Comment by petervojtek** [comment]
I rather leave this question to be answered by Jesse :) [but from UI point of view, the current behaviour is confusing for an user].

**Comment by jterps08** [comment]
we need a separate count for comments and separate score for upvotes/downvotes (e.g. +25, -13 = 12... +20, -8 = 12)... this 'score' is not the same as total votes (25+13=38 or 20+8=28)...

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/issues/231 deployed

**Comment by petervojtek** [comment]
@igaponov ,  thanks for the `comments_count` attribute.
now it seems that it's value is +1 that then actual number of comments.

Example: 
micro-petition 226 has zero comments, but comments_count = 1.
micro-petition 233 has 2 comments, comments_count = 3.

**Comment by igaponov** [comment]
To see all comments using `GET /api/{typeEntity}/{entityId}/comments/` add query param `?root=true`

**Comment by austinpapp** [comment]
doc should be up to date

**Comment by petervojtek** [comment]
ok, so the actual number of comments from backend counts for some reason also the body of the petition/post/.. as a comment, that is why it is +1. 
I fixed this by decrementing the number by 1 in JS, thought I don't understand why it is implemented this way on backend.
