### ISSUE TITLE
Home - Messages screen is not displaying data properly

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#128]
I am not sure what is supposed to be there, but this looks weird:

<img width="772" alt="screen shot 2016-07-05 at 08 40 55" src="https://cloud.githubusercontent.com/assets/225506/16575938/47e41eea-428c-11e6-8bf5-8ebdfa9f2103.png">

**Comment by jterps08** [comment]
This is the announcements screen. It's supposed to display new announcements sent by any leaders. Users cannot comment or upvote or otherwise interact with announcements. They are one-direction only. Ideally, users can easily share the announcement itself directly to their Facebook, LinkedIn, and Twitter networks. If there are no announcements to display, the share buttons should not display.
