### ISSUE TITLE
Unboosted, Unexpired Posts Appearing in Priority Zone

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#167]
Unboosted, unexpired posts should not included in the priority zone. They should not be included in counter unless boosted and not-expired. They should be sorted in priority zone unless boosted and not-expired.

I believe this is currently a backend issue.

**Comment by jterps08** [comment]
![screenshot_2016-08-05-23-01-54](https://cloud.githubusercontent.com/assets/7582457/17458989/788549f2-5bf5-11e6-9601-4a91df0e886f.png)

**Comment by jterps08** [comment]
@austinpapp Is this closed now?

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/pull/242 was deployed

**Comment by austinpapp** [comment]
can't close until we can confirm/test

**Comment by petervojtek** [comment]
@jterps08 , in frontend items in activity feed are ordered in following manner:
1. first items where `"zone":"prioritized"`
2. then unexpired items
3. then expired

there is no additional business logic, everything else is on backend.
front-end is not explicitly aware that there is "boosting".

To sum up, I believe this issue is fixed and be closed because this issue was the reason to explicitly provide `zone` information from backend to frontend. However I am unable to tell how the boosted/unboosted posts do behave at all, such information is not explicitly available in frontend.

**Comment by jterps08** [comment]
Understood @petervojtek - I've marked it "ready for retest" so that I can look at it in the test APK. Thank you!

**Comment by jterps08** [comment]
Closing this and opening new item in #212 assigned to Igor.
