### ISSUE TITLE
FB Avatar Not Displaying Correctly

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#176]
I logged in with my Facebook account and my avatar was not properly displayed in newsfeed or My profile screen. It should have shown my current FB avatar.

**Comment by jterps08** [comment]
![screenshot_2016-08-05-23-01-54](https://cloud.githubusercontent.com/assets/7582457/17458960/eff3e13e-5bf4-11e6-86fe-f0edca13b32a.png)

**Comment by igaponov** [comment]
In https://github.com/PowerlineApp/powerline-server/pull/245 I've added api doc for v1 (frontend must provide url) and service for v2 (backend does all work) to add a photo from Facebook, but it'll work only after new registration.

**Comment by jterps08** [comment]
@igaponov I want to confirm. You have added API doc for Powerline v1. Powerline backend is compatible with Facebook v2.7 or is that only a front-end change from Peter for login purposes? Thanks

**Comment by igaponov** [comment]
For v1 backend needs avatar url from frontend.

**Comment by jterps08** [comment]
Ah got it - thank you!

**Comment by petervojtek** [comment]
This bug seems to affect only facebook-powerline users which were registered more than 3 weeks ago.

Currently, when facebook user is registered to powerline via `POST https://api-dev.powerli.ne/api/secure/registration-facebook`, the facebook avatar image is provided via `avatar_file_name` and then the avatar image is properly served by backend and displayed in mobile app.

However the old users seem to miss the avatar image.. I cannot inspect that in particual for Jesse's facebook user (because I do not have you facebook credentials :), however when I login as user `Jesse1` with password, I also see that that user `Jesse1` has broken avatar image, in particular, backend is providing URL of this non-existing image:

```
http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/533dd943db89c.jpeg
```

this bug seems to be similar to #62 and I guess @austinpapp may apply the [same solution](https://github.com/PowerlineApp/powerline-mobile/issues/62#issuecomment-235241681) as applied in #62.

**Comment by jterps08** [comment]
Yes, we may need @igaponov to develop a console command for Austin to run to refresh this. I am changing priority to P2.

**Comment by austinpapp** [comment]
fyi - https://github.com/PowerlineApp/powerline-server/pull/245 was deployed

**Comment by austinpapp** [comment]
yea. i think we will need to write a script to fix the backend images. my concern here is that... we will need ot do this again and again (staging and prod). so really we have now several scripts to fix our production db. that kinda sucks and is probably something we will miss if we aren't very very on top of everything...

**Comment by jterps08** [comment]
Is this still assigned to you @austinpapp or should we assign it to Igor?

**Comment by austinpapp** [comment]
no because i wrote the script to do this.

**Comment by austinpapp** [comment]
@petervojtek please check this again. there is only 1 group that actually has an `avatar_file_name` present. `{'group' : 'austin1' , 'id' : 308 }`

if you want, i could update a few groups to point to a few files we have available in s3. at least it would show those groups with a file name. just let me know what group to update.

**Comment by jterps08** [comment]
@austinpapp I am the one that created this issue. I am logging into Powerline, with my Facebook account, and my FB avatar is not displaying properly.... It's about user avatars not group avatars. I just want to make sure that's clear.

**Comment by austinpapp** [comment]
uummm.... yea. @jterps08 you're right. sorry. i updated `avatar` column for all users if we have the s3 object present. please check again.

**Comment by jterps08** [comment]
Will test in Staging.
