### ISSUE TITLE
Tapping Hashtag from Newsfeed Doesn't Open Search Screen 

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#215]
Tapping on a #Hashtag from the Newsfeed doesn't load the Search screen. Currently, it hangs. It should load Search Screen with the results for searching for that hashtag.

**Comment by petervojtek** [comment]
I confirm the bug. I am blocked by broken API doc.

**Comment by petervojtek** [comment]
this is related to #108

**Comment by petervojtek** [comment]
first we need the backend search endpoint to be updated to properly treat the existing datatypes. currently this enpoint is deprecated:
https://api-dev.powerli.ne/api-doc#get--api-search-by-hash-tags
and tells that I should use `GET /api/v2/micro-petitions?tag=hash`, but the micro-petitions were already abandoned cca 2 months ago.

**Comment by igaponov** [comment]
@petervojtek you can use `GET /api/v2/posts?tag=hash` and `GET /api/v2/user-petitions?tag=hash`, check api doc for these endpoints please. I'll fix deprecation message.

**Comment by igaponov** [comment]
Api doc is updated

**Comment by jterps08** [comment]
Do we know why the API Doc keeps going down?

**Comment by igaponov** [comment]
@jterps08 API doc is working, what was wrong?

**Comment by petervojtek** [comment]
@igaponov , do I use the search tag request properly?

I make this request:

```
Request URL:https://api-dev.powerli.ne/api/v2/posts?tag=powerline
Request Method:GET
Status Code:200 OK

and thre response is empty:
{"page":1,"items":20,"payload":[],"totalItems":0}
```

However there exist Post 316 (created by the same user who is doing the search), which has following body and I would expect it to appear in results:

```
{"quorum_count":0,"share_picture":null,"answers":[],"is_subscribed":true,"id":316,"body":"let us try some hashtag #powerline","html_body":"let us try some hashtag #powerline","group":{"total_members":4,"id":312,"type":"group","group_type":0,"username":"Peter10Group7","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","manager_first_name":"Peter10","manager_last_name":"Peter10","manager_email":"peter10@test.com","manager_phone":"+1123","official_title":"Peter10Group7","official_description":"Peter10Group7","acronym":"10G7","official_type":"Non-Profit (Not Campaign)","official_address":null,"official_city":null,"official_state":null,"joined":1,"picture":null,"created_at":"Wed, 27 Jul 2016 12:44:56 +0000","petition_percent":null,"petition_duration":null,"membership_control":"public","fill_fields_required":false,"petition_per_month":5,"required_permissions":[],"permissions_changed_at":null,"group":null,"token":null},"created_at":"Mon, 03 Oct 2016 08:58:14 +0000","expired_at":"Wed, 05 Oct 2016 08:58:14 +0000","user_expire_interval":2,"user":{"full_name":"Peter31 Peter31","id":83,"type":"user","username":"Peter31","first_name":"Peter31","last_name":"Peter31","official_title":"Peter31 Peter31","email":"peter31@test.com","zip":"12","avatar_file_name":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png","birth":"01\/01\/1977","address1":"San Diego","address2":"12","city":"San Diego","state":"CA","country":"US","phone":"+133","facebook_link":null,"twitter_link":null,"race":null,"sex":null,"orientation":null,"marital_status":null,"religion":null,"employment_status":null,"income_level":null,"education_level":null,"party":null,"philosophy":null,"donor":null,"bio":null,"slogan":null,"interests":[],"registration":null,"token":"3z10w4c0hveoccoskgscs00gwc8s4c0ss8s44wcs8kc8wgc4gs83","facebook_id":null,"ios_device":null,"android_device":null,"do_not_disturb":false,"is_notif_questions":true,"is_notif_discussions":true,"is_notif_messages":true,"is_notif_micro_following":true,"is_notif_micro_group":true,"is_notif_scheduled":false,"is_notif_own_post_changed":true,"scheduled_from":null,"scheduled_to":null,"is_registration_complete":true,"plain_password":null},"boosted":false,"votes":[],"cached_hash_tags":["#powerline"],"metadata":{"title":null,"description":null,"image":null,"url":null}}
```

**Comment by petervojtek** [comment]
ok, I found out I have to include the '#' symbol as well in the query

**Comment by petervojtek** [comment]
@jterps08 , how should the results of searching for Posts and UserPetitions look like?
Should the look the same way as if there were in activity newsfeed (or favorites) ?

This makes sense to me as I could reuse existing html, however for some reason the backend is not serving the found Posts and UserPetitions the same format as in newsfeed (e.g. `entity` attribute is not present).

Also I do not understand how is the search API supposed to be used in future.
Currently I have to make two HTTP requests:

```
GET /api/v2/posts?tag=hash
GET /api/v2/user-petitions?tag=hash
```

to search for Posts and UserPetition. 

All the other data types (Petition, Payment, Crowdfunding, News..) are not searched. 
 If we would like to search for the, later do we want to add plenty of additional endpoints? 

I find it much easier if there would be only one api search endpoint for all the content data types ( so that i make only one HTTP request), and the search results will be provided in the same format as in the activity newsfeed. 

This kind of discussion would be actually more fruitful if is will take place before the actual implementation changes were already made to backend..

**Comment by jterps08** [comment]
@petervojtek let's have the discussion on Slack. We need to have short-term fix and a long-term fix. If they're the same thing, great. If not, ideally the short-term fix is 'step 1' along the path to a long-term fix. It's P3, but we do want search for hashtagged posts to work.

**Comment by jterps08** [comment]
Let's make the short-term fix a P2 priority and punt the long-term fix. Can we close?

**Comment by petervojtek** [comment]
@jterps08 , this is currently not working.
there are two options:
- either I will use the existing endpoints, but I will have to adapt the html to properly display the results -- cca 1-2 hours of my work (and don't know how it is actually supposed to look like), 0 hours of Igor's work
- or Igor will adapt the endpoint as I suggested above and I will be able to reuse the existing html rendering from activity newsfeed. cca 15 minutes of my work, don't know how much of Igor's time.

**Comment by jterps08** [comment]
@igaponov - Can you estimate on the above?

**Comment by igaponov** [comment]
@jterps08 so, we want to search by user post, user petition and all kinds of poll, right? I can add new endpoint for it and create this query for db, but in the future when we have a lot of posts/petitons/polls it will not work fast. It's better to use any search engine for this.
1. Add new endpoint and a query for db + tests    ~ 4 hours
2. Add search engine - much more time, because we don't use it now

So, i think db query is enough for now and in the future we can move to s/e.

**Comment by jterps08** [comment]
I think the issue is the current DB query return... @petervojtek can you clarify? I thought we just needed to repurpose existing endpoint...

I do agree that adding a search engine would be much more time and not what we want for right now...

**Comment by petervojtek** [comment]
@jterps08 

> I think the issue is the current DB query return

there are two "problems":
- one is the content of the response (which is different than the "standard" activity-items response received in activity  newsfeed and favorites)
- and other issue is that currently there has to be made one request per each data type, while from GUI point of view the user wants to search all the data types at once and look there for some #hashtag. 

But given the amount of time @igaponov will need to treat it, it is easier when he will do nothing and I will adapt the html templates to render search results properly for the existing response structure.

**Comment by petervojtek** [comment]
ok, it is working now, at least from following places:
- when you click #hashtag in activity newsfeed
- when you click #hashtag in item detail (leader content and user petition and post)

but the code is an epic mess:
- the html template is completely different than the activity newsfeed html
- I do not understand why but in code there are two different approaches how to handle the #hashtag click.. leader-content item details use some `cached_hash_tags` attribute provided by backend, while Post and UserPetition and activity newsfeed for all items (including leader content items) use another approach based on ng-click and event parsing.
- the way how the seached query is transferred from e.g. item detail to the search screen is the worst approach I could imagine. Instead of using URL parameters it is using some weird cache which gives no added value, but only makes the app behaviour non-deterministic and hard to debug.

the UI looks like this:
<img width="818" alt="screen shot 2016-10-13 at 10 23 21" src="https://cloud.githubusercontent.com/assets/225506/19343605/242e2280-9137-11e6-904e-a1fe2341197d.png">

**Comment by jterps08** [comment]
Okay, let's create an issue to fix the 'epic mess' that you refer to... I don't expect it to be a heavily used feature in the next few months anyway...

**Comment by jterps08** [comment]
this didn't seem to work for me this morning when I tested. I assume it's because I have an older build...

**Comment by petervojtek** [comment]
@jterps08 , please try with the latest version -- it is working for me. or please describe which specific scenario is not working for you so that I at least try to repeat exactly your steps.
