### ISSUE TITLE
Social Activity Feed Showing Empty Entries

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#220]
I'm not sure if this is a database issue or what...

Either data is missing, incomplete, or corrupted. I should be seeing descriptive text for most of these items and instead I'm seeing blanks. 

![screenshot_2016-09-08-09-19-28](https://cloud.githubusercontent.com/assets/7582457/18355313/b835b214-75b6-11e6-8690-a8b87d40a355.png)

**Comment by petervojtek** [comment]
may be a frontend issue due to adapting to changes in #187, will inspect it.

**Comment by petervojtek** [comment]
@igaponov , As Peter12, I see following social activity feed for Following tab:
The problem is with the third item which shows only timestamp:

<img width="763" alt="screen shot 2016-09-09 at 10 34 27" src="https://cloud.githubusercontent.com/assets/225506/18380773/43d0ecfe-7679-11e6-9cf5-1dacb0ac6b55.png">

this is the content of the social activity item:

```
{"tab":"following","html_message":null,"id":1117,"group":{"id":285,"type":"group","group_type":3,"avatar_file_path":"https://api-dev.powerli.ne/bundles/civixfront/img/default_group.png","official_title":"San Diego"},"following":{"full_name":"Peter21 Peter21","id":77,"type":"user","official_title":"Peter21 Peter21","avatar_file_name":"https://api-dev.powerli.ne/bundles/civixfront/img/default_user.png"},"type":"post-created","created_at":"Fri, 09 Sep 2016 07:51:02 +0000","target":{"id":260,"body":"Post to test #209 -- upvote/downvote Post ffrom newsfeed","type":"post"},"ignore":null}
```

the `html_message` attribute is null for this item - I am not sure if this is the intention or bug. If it is an intention, I guess I can construct the html_message locally given the `type=post-created` attribute, but if would be better if this business logic would be on backend.

**Comment by petervojtek** [comment]
@igaponov , there seems to be missing person name in `html_message` in some social activity items:

```
"html_message":"<p> voted on your post</p>"
"html_message":""<p> commented on the post you subscribed to</p>"
```

While others contain it.:

```
"<p><strong>Jesse Chen</strong> responded to a event \"bodytext\" in the <strong>San Diego</strong> community</p>"
```

**Comment by igaponov** [comment]
@petervojtek I changed messages according to https://github.com/PowerlineApp/powerline-mobile/issues/226. Or should `html_body` be the same as before?

**Comment by petervojtek** [comment]
@igaponov , just to make sure we understand each other - #226 is related to push notifications while this issue is aimed at in-app notifications displayed in social activity newsfeed.

I prefer if you could send me complete html_message (with person name) so that I don't have to construct the final message on mobile app side. 
this is because otherwise I will have to implement and maintain it actually twice (in mobile app and in web app later), which is something we want to avoid.

**Comment by igaponov** [comment]
@petervojtek social activity message = push message on backend.
I've changed html_message back

**Comment by petervojtek** [comment]
thanks Igor, I confirm now the social activity feed entries looks complete.

**Comment by austinpapp** [comment]
Can we make sure we have proper unit tests for this? We need to confirm the obj is consistent across changes.

**Comment by igaponov** [comment]
@austinpapp https://github.com/PowerlineApp/powerline-server/issues/303
