### ISSUE TITLE
Push notification: Author Notifications on Post and UserPetition comment

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#238]
1. as Pavlik Morozov I created Post 281.
2. The post has zero comments.
3. As Peter10 I add comment to the Post
4. Pavlik receives this Push notification:

<img width="299" alt="screen shot 2016-09-13 at 15 45 51" src="https://cloud.githubusercontent.com/assets/225506/18476127/2b055432-79c9-11e6-875a-2eda0a235cc6.png">

The text should be different because there is no comment by Pavlik.

For User Petition it is similar, and action buttons are missing:

<img width="309" alt="screen shot 2016-09-13 at 15 49 11" src="https://cloud.githubusercontent.com/assets/225506/18476279/b04d4da2-79c9-11e6-8558-2086e358addd.png">

**Comment by jterps08** [comment]
Correct language for both of these scenarios should be in #226

**Comment by igaponov** [comment]
@petervojtek you always reply on author's root comment, that's why you get "replied to your comment" push.
@jterps08 there is no text/buttons for `comment replied` push in #226

**Comment by jterps08** [comment]
No buttons needed. Tapping notification should open up the detail screen to show comments.

**Comment by igaponov** [comment]
@jterps08 what about a `message`?

**Comment by jterps08** [comment]
I'm not sure if I understand the scenario that we're referring to, so let me parse them out...

**Scenario 1:** If user is author of a post or user:petition, he is automatically subscribed to notifications on his own post for new comments or new upvotes. Message is Message("commented on your post") OR ("voted on your post") depending on what happened. User can unsubscribe from notifications by turning off the notifications bell. 

**Scenario 2:** If user is not the author of a post or user:petition (or any leader content item), he can opt-in to subscribe to the item to be notified of any comments on that item (not votes), message is Message("commented on the item you subscribed to"). User can unsubscribe at any time by turning off the notifications bell.  [#226 says 'post' but we can say 'item' instead so that it makes it easier for all different types of items]... 

**Scenario 3 (I think this is what you're referring to above):** If user A makes a comment on **any** item (poll/post/etc.) and user B replies to User A's comment (User B comment is child of User A comment), I thought we only had Social Activity Feed item for this scenario not push notification alert... However, if push notification alert exists for this scenario, we can keep it. User A should receive title (FirstName LastName) message "replied and said CommentText" (Reply, Ignore) where Reply opens up the comment for making a reply and where CommentText is up to 284 characters of the comment.

Due to the 'root comment' situation, Scenario 1 and Scenario 3 may conflict with each other if User A creates the post/user:petition/poll/fundraiser/whatever and User B makes a comment on the item. I don't understand exactly how the backend works, but if the system sees User B's comment on the item as a reply to the root comment, I would prefer implementing the message in Scenario 3. 

We can come back later and update Scenario 2 language to be similar to Scenario 3 language (with CommentText etc). Doesn't need to be re-done if you already did it...

**Comment by petervojtek** [comment]
@igaponov,

> you always reply on author's root comment, that's why you get "replied to your comment" push.

I technically understand you, but the average user has no idea you use some root comment concept to implement the discussion and will be confused :)

**Comment by petervojtek** [comment]
this is how the User Petition comment notification looks for an author of the Petition:

<img width="307" alt="screen shot 2016-09-15 at 15 00 38" src="https://cloud.githubusercontent.com/assets/225506/18550663/38cf7902-7b55-11e6-829a-ebe5a5ae8bda.png">

while in case of Post it looks as following:

<img width="306" alt="screen shot 2016-09-15 at 14 59 33" src="https://cloud.githubusercontent.com/assets/225506/18550676/43364830-7b55-11e6-99ea-91d713efc2b9.png">

@jterps08 please confirm this is what you want..

**Comment by igaponov** [comment]
fixed

**Comment by jterps08** [comment]
For author of petition, notification language should say  "commented on your petition" (if author) and "commented on the petition you subscribed to" (if not author). 

For author of post, notification language should say "commented on your post" (if author) and "commented on the post you subscribed to" (if not author).

**Comment by petervojtek** [comment]
ok, works.
