### ISSUE TITLE
iOS: Difficult to tap Menu Burger Icon given vertical appearance

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#256]
User tries to tap on burger icon, but burger icon is on top of where the "cellular strength" icon usually is making the tappable area difficult to act on.

**Comment by jterps08** [comment]
It seems this entire 'row' is difficult to tap on (new post icon or back button when it replaces menu burger icon)...

**Comment by jterps08** [comment]
If you have the bandwidth to do this while waiting on push notifications, I think this would help with usability Peter

**Comment by petervojtek** [comment]
yes, I confirm this issue @jterps08 , I thought it affects only my iPhone4s. good to know you can reproduce the problem as well, I will address it.

**Comment by petervojtek** [comment]
ok, I fixed it, though the UI experience is now different on iPhone6 and iPhone4s, which is probably due to different screen size.

on iPhone6, the iOS status bar is now above the app  and thus is not overlaying the powerline menu button (the app does not occupies the top 20px of screen).
on iPhone4s, the iOS status bar is not visible at all and Powerline app is running fullscreen.
This makes sense to me as the iphone 4s screen estate is much smaller and every pixel counts.
