### ISSUE TITLE
Tapping Favorite Star does not turn to yellow in newsfeed immediately after saved to favorites

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#261]
When user taps the Favorite star, the icon should turn yellow/unyellow immediately in the newsfeed. Toast displays correctly when item is saved to Favorites. Tapping second time to remove from favorites does not work (instead Toast says "saved to favorites" again, and it should say removed from favorites message). Item is never actually saved to Favorites. 

Tested on iOS

**Comment by petervojtek** [comment]
I cannot reproduce the bug @jterps08 . Maybe you had some network issues at the time of testing, because the star/unstar works as following:
1. you click the star icon
2. http request is made to add the item to favorites
3. only when the request is successful, the icon will change color and toast is displayed.

when step 2. failed due to network issues, step 3 was not performed.
