### ISSUE TITLE
iOS My Representatives Screen Not Showing

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#262]
User taps on My Representatives icon in menu and a blank screen is shown.

**Comment by petervojtek** [comment]
there is missing some message "there are no representatives for you", thought I am not sure if it is expected behaviour that user will have not representatives.

Anyway, whan you enter the Representatives screen, following request is made:

```
Request URL:https://api-dev.powerli.ne/api/representatives/
Request Method:GET
Status Code:200 OK
```

and for e.g. user `Peter10`the response is empty array. Some actions should be taken on backend to assign representatives to an user.

**Comment by jterps08** [comment]
This user minotest had a Hoboken New Jersey address so we should have been able to see the same representatives that I had. I do not know why it was not loading the screen correctly.

**Comment by petervojtek** [comment]
@jterps08 , this is what I see in Representatives screen when I login as `minotest` on iOS emulator:

<img width="355" alt="screen shot 2016-09-19 at 15 31 43" src="https://cloud.githubusercontent.com/assets/225506/18633774/41128588-7e7e-11e6-8171-e462c8c2d9c7.png">

**Comment by jterps08** [comment]
Hmmm. Yeah, I was unable to see any of that. Maybe it was a bad Internet connection. I can test again later. Chris is not here right now.

**Comment by jterps08** [comment]
If you can confirm @petervojtek on simulator, I am okay with you closing this for now.
