### ISSUE TITLE
Viewing Item from Notifications Drawer ("View" button) shows Item Detail Screen with no back button

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#267]
User shows Post Detail Screen, but is unable to move back when opening an item from the notifications drawer

Tested on Android

**Comment by petervojtek** [comment]
@jterps08 , there is "problem" with this use case in general  - to jump into to app into some specific view and have the back button avaiable out of the box. There is not proper support for that in ionic framework, so I hacked it in following manner:
1. when you click View (or amost any button in notification), the Powerline app is opened and you are headed to Main screen
2. after 1 second, you are automatically redirected to the desired Post/Petition/whatever detail so that you have some "browsing history" in the app and thus the back button is loaded with content.

Maybe the 1 second was not enough in your case. I increased the waiting time on 2 seconds, let's see if you will face this bug again. If yes, there is another solution, but takes longer to implement and thus I avoided it so far.
