### ISSUE TITLE
Notification Action Button: New Post by Followed User "Upvote" button  should show Item Detail Screen and Upvote submitted

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#289]
It seems that the Upvote button records the Upvote, but maybe its because the "Submit" button still shows that is making this confusing? Maybe user should see "undo" button if already answered.

Also, "Ignore" option should only be available on boosted posts, not non-boosted posts.

**Comment by jterps08** [comment]
I basically want to make sure it's actually 'upvoting' the post (not simply showing the post detail screen). can you confirm? If so, there's no work to be done for 289

Again, this might be a UX issue. The "submit" button is still shown to me even though I already answered. Maybe this issue would be solved if it said "Undo" instead (if not expired).?

**Comment by petervojtek** [comment]
I cannot reproduce the behaviour, because the push notification does not seem to be created on server.

Steps:
1. user `peter.vojtek` is following user Peter10
2. user Peter created post 304 in group 310 (both users are members of the group 310)
3. there is not new entry in `/dev/shm/powerline/logs/push_dev.log`

**Comment by jterps08** [comment]
(Just to confirm - @petervojtek took the correct steps here and Step 3 should have generated push notification. This is working in production and was working, I thought in a test build recently...

**Comment by petervojtek** [comment]
ok, the notification arrives. 
Now I understand the first Jesse's comment.
Yes, the Upvote is taken into account, and yes, it is confusing that the button text is Submit at the time.

fixed it so that current behaviour is following:
1. You click Upvote in the notification
2. Post detail is displayed to you, Upvote option is selected, and the button below holds text "Undo". If you choose other option, it will turn to "Submit"
3. Toast is displayed telling "Your vote was recorded"
