### ISSUE TITLE
Payments Not Occurring on Poll:Payment

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#304]
I extracted this issue from #281

**Comment by petervojtek** [comment]
ok, so once again:
1. `Peter10` is leader in group San Diego and he created poll:payment with ID=303 and added there three options:

```
{"votes_count":0,"id":499,"value":"thank you","payment_amount":10,"is_user_amount":false}
{"votes_count":0,"id":500,"value":"thank you more","payment_amount":20,"is_user_amount":false}
{"votes_count":0,"id":501,"value":"this is user amount","payment_amount":99,"is_user_amount":true}
```
1. Now as `Peter31` who is member of group San Diego, I pick the first option and want to answer (pay it), but I experience this:

```
Request URL:https://api-dev.powerli.ne/api/v2/polls/303/answers/499
Request Method:PUT
Status Code:500 Internal Server Error

{"comment":"","privacy":0,"payment_amount":10}

XMLHttpRequest cannot load https://api-dev.powerli.ne/api/v2/polls/303/answers/499. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 500.
```

But the payment/answer seem to have proceeded, because when I refresh the page, I see this:

<img width="678" alt="screen shot 2016-09-29 at 09 29 10" src="https://cloud.githubusercontent.com/assets/225506/18944719/3fe581e6-8627-11e6-8aff-8e8a6c955f91.png">

And in JS console I see following error:

```
Failed to load resource: https://api-dev.powerli.ne/api/answers/212/charges/ Failed to load  the server responded with a status of 404 (Not Found)
```

**Comment by igaponov** [comment]
@jterps08 there is we have the next situation: user is trying to pay the payment request, but the group that owns this request doesn't have a bank account (in stripe). What should we do? I think the group should not be able to create payment request if it doesn't have a bank account.

**Comment by jterps08** [comment]
Correct @igaponov - In the old frontendbundle, the leader was unable to create a paymentrequest (fundraiser) if there was no bank account setup in Stripe for that group's account.... We need that implemented. 

Similarly, @petervojtek - the system registered your poll choice, but did not register payment. If it had registered payment correctly, the receipt screen should have displayed a transaction number with the amount... Ideally, if payments aren't successful, this screen should not be showing that the person donated. It should kick an error back to the user and give them the chance to try again. 

Open to other solutions, but that's how I think it should work...

**Comment by igaponov** [comment]
@jterps08 also, there are old API endpoints to create Stripe customers and accounts (add bank card and bank account), but it works only for groups, not for users (you need to be logged in as a group, we had the same problem with a leader content). So we probably need to change it now.

**Comment by jterps08** [comment]
I'm not sure what the best approach is @igaponov ...

Here's what I know:
Only the group owner should be able to change the group subscription (silver/gold/free/etc.).
A user may own multiple groups. A user may be a manager of multiple groups.
Any group leader (owner or manager) should be able to create a fundraiser in a group, but only if the group has a bank account or bank card setup for Stripe transfer of collected funds.
In order to setup bank account or bank card, the group will need to provide certain information to Stripe (CC number, EIN or SSN, other info as defined by STripe). 

When a group runs a fundraiser, I believe the funds should be sent back to the entity not to the user. For example, if I am president of Save the Whales, people are donating to STW not to Jesse Chen... So, fundraiser money should go back to STW, not to Jesse Chen's personal account. If Austin is Vice President of Save the Whales, people are donating to STW, not to Austin Papp. So, fundraiser money should go back to STW, not to Austin's account. 

Does that make any sense?

**Comment by jterps08** [comment]
@igaponov can you describe the solution in powerline-server #347? Just want to make sure I understand how it works now...

**Comment by igaponov** [comment]
@jterps08 
1. I've added an endpoint to create a bank account for group
2. I've added an endpoint to add bank card for user
3. I've added a check when somebody tries to create payment request (not crowdfunding) without bank account
4. Added an exception for error above, so Peter will get normal error message now instead of `No 'Access-Control-Allow-Origin' header is present ...`

**Comment by jterps08** [comment]
Ok, so @petervojtek if someone tries to create fundraiser and specific error is returned per Igor above, then we will need to prompt the user to setup bank account for group. I can provide precise language for this error in Slack when it comes time to address in web app or mobile app.

**Comment by petervojtek** [comment]
ok, I cofirm that when I try to repeat what I have done [here - -i.e. create a poll:payment](https://github.com/PowerlineApp/powerline-mobile/issues/304#issuecomment-250391285), I receive:

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/285/polls
Request Method:POST
Status Code:500 Internal Server Error

{"code":500,"message":"You must have a Stripe account to create a payment request.","errors":null}
```

and I will display some alert that user must setup card for that group first -- this will be actually relevant when we will add UI to add new leader content (poll:payment and poll:crowdfunding) .

**Comment by jterps08** [comment]
Alert: "Your group must have a bank account verified before you can publish a fundraiser. Please visit Group Settings to setup and verify bank account information."
