### ISSUE TITLE
Create Leader Content -- Ability to Add Attachments

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#338]
from #309.

attachment types:
- image
- video
- text

**Comment by jterps08** [comment]
@igaponov please confirm backend can support attachments (aka 'educational context')

**Comment by igaponov** [comment]
https://api-dev.powerli.ne/api-doc#get--api-v2-polls-{poll}-educational-contexts
https://api-dev.powerli.ne/api-doc#post--api-v2-polls-{poll}-educational-contexts
https://api-dev.powerli.ne/api-doc#delete--api-v2-educational-contexts-{id}

**Comment by jterps08** [comment]
We need to confirm that the newsfeed can accurately display attachments (namely, picture and video) because we haven't been able to test that since the switch to v2 api. When we're testing this, it may be a good idea to test meta data as well for embedded link preview...

**Comment by petervojtek** [comment]
@igaponov , can you give me some hint what should be the payload when creating educational content (i.e. attachment)? I cannot find the payload description in the [API doc for `POST /api/v2/polls/{poll}/educational-contexts`](https://api-dev.powerli.ne/api-doc#post--api-v2-polls-{poll}-educational-contexts)

**Comment by igaponov** [comment]
@petervojtek docs are fixed

**Comment by petervojtek** [comment]
@igaponov , I can add photo attachment successfully.
but when I try to add  1x video and 1x photo to a petition, I can add the video successfully but then experience this with the photo:

```
Request URL:https://api-dev.powerli.ne/api/v2/polls/457/educational-contexts
Request Method:POST
Status Code:400 Bad Request

{"type":"photo","content":"https://images.pexels.com/photos/34676/pexels-photo.jpg?h=350&auto=compress"}


{"code":400,"message":"Validation Failed","errors":{"errors":["This poll should contain 3 educational contexts or less."],"children":{"type":[],"content":[]}}}
```

If I count properly I add two attachments (1x video, 1x photo - fails above).

**Comment by petervojtek** [comment]
@jterps08 , can you please add/confirm details on how the attachments should be provided when creating leader content?
- video: is submitted as url, i.e. the user will copy and paste the video url to the create new petition/poll/.. form.
- text -- user will write/paste the text into textarea. I am actually not sure what is the purpose of text attachment (given that I can write the text directly into e.g. petition body.
- image -- should user provide URL (as with video), or pick a file from phone library (api seems to support the later approach)?

**Comment by jterps08** [comment]
video is URL
text is text (it's for extra information that is not included in main petition body... we might get rid of this eventually, but we might as well keep it right now)
image is a file from the phone library.

**Comment by petervojtek** [comment]
@jterps08 , and regarding the cardinality of attachments, I guess following makes sense, please confirm:
- text - only one such attachment
- photos - many
- videos - many

**Comment by jterps08** [comment]
agreed, no more than 3 total attachments max please (e.g. 2 photos 1 video, 3 videos... 3 photos... 1 text 2 videos, etc)

**Comment by petervojtek** [comment]
@jterps08 , it's done.

when creating a new leader content (except announcement), on bottom of the form is a button "Add attachments". When you click it, following form will expand:

<img width="396" alt="screenshot 2016-11-18 09 56 44" src="https://cloud.githubusercontent.com/assets/225506/20424299/63f1bf94-ad75-11e6-8b30-2c995a562822.png">

**Comment by jterps08** [comment]
fantastic - thank you @petervojtek 

and just to confirm - when the attachment is displayed in the newsfeed, it's being processed through imgix, right?

**Comment by petervojtek** [comment]
> when the attachment is displayed in the newsfeed

@jterps08 , regarding image attachments -- when adding attachment, image is send to backend as B64 encoded string.

when displaying attachment, backend sends the image as B64 -- it is not served via URL from imgix.

**Comment by jterps08** [comment]
@petervojtek for performance reasons: If we upload a file to Powerline servers, it is uploaded without compression per se. When we display the image, we want to display it via Imgix.

Additionally, I will create a separate issue for attached images/videos appearing in the newsfeed. They have not been appearing (we also have not tested this since March).

**Comment by petervojtek** [comment]
> When we display the image, we want to display it via Imgix.

@jterps08 , I don't know how to proceed. the API does not seem to describe this process:
https://api-dev.powerli.ne/api-doc#post--api-v2-polls-{poll}-educational-contexts

and I searched the frondend code and there is no existing business logic which is meant to upload images directly to Imgix. images which are produced on frontend, e.g. profile photo, are processed this way: 
* frontend uploads the photo to backend
* and then backend deals with the Imgix

**Comment by igaponov** [comment]
@jterps08 currently we have only one image displayed via imgix: avatar in push notification. I don't remember issues for other images.

**Comment by jterps08** [comment]
@petervojtek images are not supposed to be stored on imgix. They're supposed to be stored on Powerline servers. @igaponov the backend is working correctly. No changes are needed to backend. 

@petervojtek - when we *display* an image in the frontend, we are retrieving the URL for the image from Amazon S3. We need to leverage the imgix pre-fix when displaying the image so that it is compressed/processed on-the-fly by imgix. We do not want 5MB attached images loading in the newsfeed at full-size - we ran into this problem last year which is why we turned to imgix... We need images to be processed and displayed by imgix in the newsfeed and also in the item detail screen where they are displayed. It involves adding a simple pre-fix in front of the URL that the backend provides.

The reason that we implement the pre-fix on the frontend and not on the backend is because, in the future, we can customize the implementation so that the prefix is different depending on your device (mobile vs web) which the backend can't see.

**Comment by petervojtek** [comment]
@jterps08 , I miss the details on how am I supposed to change the current workflow:

current workflow:
1. user adds image as an attachment, i.e. I have the image in frontend code in B64 format.
2. currently i upload the image as B64 via [this endpoint](https://api-dev.powerli.ne/api-doc#post--api-v2-polls-{poll}-educational-contexts). 
 * if I should upload it to another endpoint, please specify the endpoint URI
3. currently I use [this endpoint](https://api-dev.powerli.ne/api-doc#get--api-v2-polls-{poll}-educational-contexts) to get the image -- backend serves the image as B64.
 * if I should obtain the image via different URI, please specify the URI

**Comment by igaponov** [comment]
@petervojtek the problem is that you pass param `type` = `photo`, but according [this endpoint](https://api-dev.powerli.ne/api-doc#post--api-v2-polls-%7Bpoll%7D-educational-contexts) it must be `image`. I'll add check for this.

**Comment by jterps08** [comment]
I'm not sure if we're all on the same understanding here...

The way imgix is currently used to process and serve user avatars is the way it needs to be used for image attachments that appear in the newsfeed (and item detail screen's "more" tab) too.

1. Leader Z creates leader content in Save the Whales group
2. Leader Z attaches 5MB image to leader content
3. App uploads 5MB image to backend (stored in Amazon S3 bucket).
4. Leader Z publishes content to Save the Whales group with attachment.
5. User A is Save the Whales group member.
6. User A opens app and looks at newsfeed.
7. User A can see Leader Z's leader content in newsfeed. 
8. The attached image is displayed in the newsfeed <-- This is not happening.
9. The attached image is displayed to the user in the newsfeed using imgix <-- This is not happening.
10. The attached image is also displayed in the "more" tab of the Item Detail Screen <-- This is working.
11. The attached image is displayed in the "More" tab using imgix <-- Unclear if this is happening or not.

Assumption: When the backend provides the URL address for the avatar, it is providing an Amazon S3 location e.g. something that looks like this full URL (e.g. https://s3.amazonaws.com/prodpowerline/avatars/106_52ce8657a6047.jpeg) OR potentially just the folder+file name only (e.g. "avatars/106_52ce8657a6047.jpeg")... I do not believe that the backend is currently providing either with the Imgix-prefix already appended for avatars, but it could be.

If my assumption is correct... then...

When the backend provides the URL address for the attached image for leader content, it should be providing an Amazon S3 location e.g. something that looks like this https://s3.amazonaws.com/prodpowerline/educational/51ef30b1038b2.jpeg 

And

When the frontend displays the image in the mobile app, it needs to display it using imgix so that we're not loading a 5MB file into the newsfeed or into the more tab. This will work similar to the way it works for user avatars in that a prefix will be appended by the frontend on top of whatever URL the backend gives us. 

https://docs.imgix.com/setup/serving-images

@petervojtek and @igaponov -- You guys need to be aligned on what the backend is providing to the frontend. Is it a full image location from S3? Or is it partial so that it can be plugged into the imgix prefix/string as shown in the link above? I would suggest that we continue to use the same approach that we use for avatars currently.

Either way, I need imgix to process image attachments that are displayed in the newsfeed and in the more tab...

**Comment by igaponov** [comment]
@jterps08 I've already [explained](https://github.com/PowerlineApp/powerline-mobile/issues/338#issuecomment-262521798) the problem above. Backend returns base64 encoded data instead of url because of wrong `type` attribute.

**Comment by jterps08** [comment]
Ahhh okay @igaponov -- this is my lack of technical understanding of what base64 is. Thank you for this.

**Comment by petervojtek** [comment]
thanks for help @igaponov , my mistake with the `photo` vs `image`.

so currently it seems to work as following. I upload the B64 image tagged as `image` and this is how I receive it:
```
Request URL:https://api-dev.powerli.ne/api/v2/polls/486/educational-contexts
Request Method:GET
Status Code:200 OK

[{"id":75,"text":"58369000b66d6.jpeg","type":"image","imageSrc":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/educational\/58369000b66d6.jpeg"}]
```

From frontent point of view it works well, I am just not sure if I should do something additional with the URL prior rendering it (jesse suggested adding some imgix prefix or so).
