### ISSUE TITLE
add group management features

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#356]
- DONE: subscription plan - #357
- DONE: membership control - #355 
- DONE: payment setup - #373
- DONE: group permissions - #358
- DONE: manage group users - #375
- DONE: invites - #372
- DONE: sections/subgroups - #337
- DONE: basic group settings (profile setup) - #374
- DONE: manage required fields: #384

**Comment by jterps08** [comment]
A few things to keep in mind. This doesn't exist in the web app, so you'd have no way of knowing this otherwise...
1. Only group owners (not managers) can change subscription plan or setup payments.
2. In "Manage group users", only group owners (not managers) can assign/remove 'group manager' privileges to their users. 
3. The backend may or may not determine what settings you are allowed to change based on the group's subscription level. I do not know. 
4. For example: membership controls (passcode/etc), micropetition controls (quorum/etc), required fields, and group divisions are all supposed to be for Silver subscriptions and above only. I'm uncertain as to whether or not those permissions were limited at the frontend or the backend with the previous frontendbundle setup.
5. Its unclear to me whether or not we can invite more than X e-mail addresses at a time to join a group at the Silver and above level compared to at the free level. 

@igaponov - It's been so long since I designed these packages that I forget what we have and what we don't have. Is there an easy way for you to tell us what special features are for Silver and above _vs_ Gold and above? I know that Free groups can be of any size, but that Silver groups can only be up to 1000 members and cannot be for business-type groups. Gold is limited to 5000 members. If a group exceeds their membership count (e.g. Save the Whales goes from 1000 members at Silver to 1001 members, the system should bump them up to Gold)... Please let me know what logic currently exists and then we can determine what changes may be made to address gaps. Thanks.

**Comment by petervojtek** [comment]
@jterps08 , how do you want to deal with following issue?

the gui is supposed to contains several sections as shown above which may expand/collapse.
user will click change settings in several sections and then click Save button in top right corner.

However due to the fact that several sections has been altered (e.g. membership control and group permissions), clicking that Save button will trigger several http requests (because alter membership control has different api endpoint than alter group permissions). Now what may happen is that the first http call will proceed successfully (alter membership control ) but the second will fail due to some validation or other problem...  now the form will be "half-saved".

 i.e., it is not possible with current backend api to have a "single-transaction save".

Solutions:
- One option would be to have a small "save" button near each section instead of one large Save button.
- other option is to have only one save button and provide following msg in the scenario described above "Membership control settings were updated successfully. There was following problem when saving the group permissions: .." -- this is not good approach from UX point of view as user may be confused.
- alter the backend to have a single endpoint to submit the whole form. probably very time consuming.

**Comment by igaponov** [comment]
@jterps08 

| Package | Invite By Email Limitation | Group Division Limitation | Announcement Limitation | Micropetition Limitation | Group Size Limitation | Group Join Management Available | Targeted Petition Fundraising Available | Targeted Petition Fundraising Price | Sum For Petition Invites | Petition Data Email Price |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Default | none | none | none | none | none | true | true | 5 | 0 |  |
| Free | 100 | -1 | 5 | -1 | - | false | false | - | 25 | 10 |
| Silver | none | none | 50 | none | 1000 | - | - | - | 15 | - |
| Gold | none | none | none | none | 5000 | - | - | - | - |  |
| Platinum | none | none | none | none | - | - | - | - | - |  |
| Commercial | none | none | none | none | - | - | - | - | - |  |

where `-` = default value

**Comment by jterps08** [comment]
Thanks Igor and thanks Peter.

Maybe we should trigger a Save/Cancel for each section? When expanding
sections, the app checks if you made any changes in the current section and
if so whether you want to keep them or not before proceeding to next
section?

Otherwise a Save/Cancel similar to My Profile screen could be leveraged for
each section but we'd want a visual alert that signals the user to save or
cancel their changes before proceeding to next section.

Your choice at this point.

**Comment by petervojtek** [comment]
ok, so all the group management subtasks are done.

**Comment by jterps08** [comment]
Well done @petervojtek and thank you.
