### ISSUE TITLE
Android: Small Image in Notifications

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#360]
Every notification should arrive with large image and small image. Currently, large image behavior is working correctly. Small icon is not working correctly.

Small icon should display the Powerline logo 'p' instead it is white. Please see screenshot below (TBD)

**Comment by jterps08** [comment]
![screenshot_2016-10-14-07-27-17](https://cloud.githubusercontent.com/assets/7582457/19615993/df15380e-97d6-11e6-8a1c-a2db16e90960.png)

**Comment by jterps08** [comment]
This little white circle image needs to change to the Powerline logo. 
The larger image is currently working correctly.

**Comment by petervojtek** [comment]
@jterps08 , I will need the Powerline logo where there will be only the person on a transparent background.

the issue is I need to re-generate the small notification icons ([this tool is perfect for it](http://romannurik.github.io/AndroidAssetStudio/icons-notification.html)) but it does not works with the current png logo image I have because it has blue background (not transparent).

**Comment by jterps08** [comment]
@petervojtek apologies I did not see this sooner. I will send you illustrator file via Slack

**Comment by petervojtek** [comment]
done.
it looks like this:

<img width="305" alt="screenshot 2016-12-05 07 52 00" src="https://cloud.githubusercontent.com/assets/225506/20876263/07f06854-bac1-11e6-9aba-418a9c033943.png">
<img width="304" alt="screenshot 2016-12-05 07 51 54" src="https://cloud.githubusercontent.com/assets/225506/20876264/0b067ec0-bac1-11e6-9289-c07c50e9e101.png">

**Comment by jterps08** [comment]
Perfect!
