### ISSUE TITLE
Favorites Screen Title and Button Issue

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#37]
When the user selects "Favorites" from the Main Menu, the Favorites screen should be titled "Favorites" (instead of Powerline) and the Menu '=' icon should be replaced with a back arrow button. It should only be a feed (no group selector, and no icons for newsfeed/social-activity-feed/announcements).

**Comment by petervojtek** [comment]
@jterps08 ,  I am trying to render list of bookmarked items. I don't know how is the list supposed to look like, but I guess it should be similar to the newsfeed, e.g. each activity should exhibit at least its author, title and description. 

However `GET /api/bookmarks/list/` is not providing the bookmarked item's title and description and I am not sure if this is intentional or not.

E.g., here is `GET /api/bookmarks/list/` for `Peter10`, containing two bookmarked items:

```

{"id":10,"item_id":175,"type":"post","created_at":"Mon, 04 Jul 2016 06:47:08 +0000"},

{"id":9,"item_id":178,"type":"petition","detail":{"id":178,"group":{"id":6,"type":"group","group_type":2,"avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","official_title":"California","acronym":"CA","group":{"id":1,"type":"group","group_type":1,"avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","official_title":"The United States of America","acronym":"US"}},"created_at":"Fri, 01 Jul 2016 06:51:52 +0000","expire_at":"Sat, 02 Jul 2016 06:51:52 +0000","user":{"full_name":"Peter10 Peter10","id":73,"type":"user","username":"Peter10","first_name":"Peter10","last_name":"Peter10","avatar_file_name":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"publish_status":0,"type":"quorum","options":[{"id":1,"value":"Upvote","votes_count":0},{"id":2,"value":"Downvote","votes_count":0}],"cached_hash_tags":[]},"created_at":"Mon, 04 Jul 2016 06:45:00 +0000"}
```

I can gather the missing title and description by calling additional GET for each of the items, however I am not sure if this is how the API is supposed to be used -- e.g. when there will be 10 favorite items, just to render the list of favorites will require 10+1 http get requests.

**Comment by austinpapp** [comment]
so in this case we are simply missing the detail attribute of the post (id:10) ?

**Comment by petervojtek** [comment]
hi @austinpapp , I am not sure what you mean by detail attribute.
If Favorites should be rendered the same way newsfeed is rendered, there should be at least following attributes:
- title
- description
- author
- group_id
- created_at

As you can see, this one is missing almost all of them: `{"id":10,"item_id":175,"type":"post","created_at":"Mon, 04 Jul 2016 06:47:08 +0000"},`

However I am not sure how Favorites are meant to be rendered - I have not seen the design and I don't think the former code was working at all.

**Comment by jterps08** [comment]
Ideally, we want the items displayed in the same format as they are on the newsfeed. If this was not properly designed from a backend standpoint to minimize API calls, let's fix the backend instead and delay this.

**Comment by jterps08** [comment]
Austin/Igor - can you give your input on this? I think Habibillah was the one who created original Favorites call.

**Comment by austinpapp** [comment]
if we want this as a similar feel to the newsfeed, we just need to make sure we return the attributes about the content as what the newsfeed returns. should be simple enough.

**Comment by jterps08** [comment]
It should basically look the same as the news feed.

**Comment by igaponov** [comment]
@austinpapp @jterps08 
Some technical thoughts. I see three implementations of this feature.
1. We leave it as it is, put info about bookmarked item to `detail` attribute and expose it in API. Pros: the fastest query. Cons: not trivial to save bookmark; if original item is deleted, link will lead to nothing (404 probably if app is trying to get item).
2. We leave it as it is, join other tables by foreign key and type. Pros: can filter bookmarks with deleted items on backend, but they will still exist in db. Cons: the slowest query.
3. Create different tables for every type of bookmark (`bookmark_petition` for example). This can be done with Doctrine table hierarchy. Pros: if we delete item, bookmark will be deleted too (by foreign key, db will keep consistency); fast query. Cons: takes more time to implement that previous variants.

**Comment by austinpapp** [comment]
i like fast queries and quick wins.. anyway, i dont want to spend too much more time on this because it's really not a critical feature. with that said, you see 1 has changing _how_ the bookmark is saved? also, if its deleted, we just show the 404. i really dont mind that right now. we can always come back to this as a bug fix later and fix when we have time, energy, money and more users.

**Comment by igaponov** [comment]
@austinpapp so you prefer the first implementation, right?

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/issues/187 was deployed.

**Comment by petervojtek** [comment]
discussion goes [here](https://github.com/PowerlineApp/powerline-server/issues/187#issuecomment-234491583)

**Comment by petervojtek** [comment]
blocked by #149

**Comment by petervojtek** [comment]
ok, so it is done. favorites are served and rendered in the same format as newsfeed items.
