### ISSUE TITLE
group management: unable to delete bank account 

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#400]
there is no API endpoint for that.

**Comment by petervojtek** [comment]
@igaponov , deleting bank account fails with following error:

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/295/bank-accounts/ba_1999m0IeRFe1HA1nmkwdagix
Request Method:DELETE
Status Code:500 Internal Server Error

{"code":500,"message":"You cannot delete the default external account for your default currency. Please make another external account the default using the `default_for_currency` param, and then delete this one.","errors":null}
```

**Comment by igaponov** [comment]
The error message is clear, you can't delete the last bank account, need to add another one first.

**Comment by jterps08** [comment]
From a user standpoint @igaponov , we need to provide the user with the ability to change their bank account information for collecting funds from fundraisers.... 

@petervojtek - We had a similar problem in a previous version where we could not remove a bank account because of the fact that we had already published a fundraiser / there were open fundraisers that prevented us from removing the bank account (would conflict with logic that requires bank account to send fundraisers.

One idea is to create a 'disabled' flag of some sort... User goes to remove/disable bank account, system stores default bank data in there as a placeholder (e.g Powerline's bank account), and disables the ability for the group to create fundraisers until the bank data is updated. 

I'm open to other ideas too, including a simple error message "You have created fundraisers in this group so you cannot remove your bank account. However, you can change your bank account information."

Open to other suggestions...

**Comment by igaponov** [comment]
@jterps08 it's possible to delete a bank account now, you just need to add another one (that will become default) before.

**Comment by petervojtek** [comment]
hmm... maybe @jterps08  will tell how the workflow is supposed to work.

From my point of view -- I do not see any reason why a group should have assigned more than one bank account. And as a group owner, I would appreaciate if I could be allowed to completely remove any bank acount I associated with powerline (for the sake of feeling of security).

for example:
1. group was Silver.
2. I change it to Free.
3. I would like to remove the bank account and cards associated with the group.

**Comment by igaponov** [comment]
@petervojtek I'm not sure if Stripe allows it, because this error comes from Stripe. Maybe it's possibe only to remove group's account

**Comment by jterps08** [comment]
I agree with Peter... As a group leader, I want the ability to remove my payment information from the system in general, but especially when I downgrade to Free... Everything is stored securely via Stripe, but it still is problematic from a user experience standpoint... 

Apparently Stripe does allow you to delete a bank account: https://stripe.com/docs/api#customer_delete_bank_account and a credit card: https://stripe.com/docs/api#delete_card

If user deletes a card for a group, then that group needs to be moved to Free subscription

**Comment by petervojtek** [comment]
ok, so here is task for me: 

> If user deletes a card for a group, then that group needs to be moved to Free subscription

**Comment by jterps08** [comment]
Agreed @petervojtek

**Comment by jterps08** [comment]
It's still unclear whether or not we can truly remove a bank account. If so, we'll need to make sure people can't create fundraisers without bank account... 

If we can't truly remove a bank account, we're going to have to come up with a solution to 'blank-out' the information...

**Comment by petervojtek** [comment]
@jterps08 , currently it not possible to remove the only bank account, server throws error:

```
{"code":500,"message":"You cannot delete the default external account for your default currency. Please make another external account the default using the `default_for_currency` param, and then delete this one.","errors":null}
```

**Comment by jterps08** [comment]
@igaponov - Why does the server throw this error? If there are active fundraisers, I understand why the user can't remove the only bank account... but if there are no fundraisers, Stripe does allow it per the documentation link above... do you know why?

**Comment by igaponov** [comment]
@jterps08 stripe allows to delete a bank account except the default one

**Comment by jterps08** [comment]
@igaponov @petervojtek I'm not sure of what the best solution is here. We want to give a group the ability to remove their bank account information from Stripe records, but we also need to have information on file per Stripe. A couple ideas:

1) Does it make sense to delete their Stripe account? This could work _only_ if the group's subscription was unaffected.
2) Alternatively, if idea #1 can't work, maybe we can update the bank account for the group to have our bank account. If we did this, however, we would need a method by which to track this so that the group would not be able to fundraiser with our information - they would need to have a real bank account. 

I'm open to other ideas. It's not something that keeps us from going live, but it is a problem I want to solve...

**Comment by igaponov** [comment]
@jterps08 if Stripe doesn't allow to delete default bank account we should delete entire account I think.

**Comment by jterps08** [comment]
If we delete entire account, will it impact the group's subscription?

Here's the scenario I'm thinking about:
1. Group A subscribes to Silver plan (and provides required CC information)
2. Group A setups bank account
3. Group A creates fundraiser
4. Group A is done with fundraiser
5. Group A wants to remove bank account
6. --what happens here? ---
7. Group A still has a Silver plan and still needs to have a CC on file
8. -- Will silver subscription be impacted? --

I would rather give user only ability to update/edit bank account information rather than remove entire account including CC on file...

**Comment by igaponov** [comment]
@jterps08 subscription belongs to `customer` entity is Stripe, deleting of `account` shouldn't affect it.

**Comment by jterps08** [comment]
Right because the group is a Powerline customer and the group is also a "seller" when they fundraise, so they have their own managed account on our platform... So customer and managed account are separate entities in the database. One can setup a bank account to fundraise without being a subscriber (account only), OR become a subscriber without fundraising (customer only), OR become a subscriber and fundraiser (account and customer entities)... Okay, let's add the remove capabilities as a deletion of account...

**Comment by jterps08** [comment]
Igor - There may be an error that occurs when someone tries to donate to a fundraiser for an account that has been removed after the fact... 

If Save the Whales publishes a fundraiser today at 12PM and 5 people donate and then they remove their account at 9PM and I try to make a donation at 10PM, the system should give an error. I don't need the error handling right now because I think this will be a rare situation, but please confirm that this is what would occur.

**Comment by igaponov** [comment]
@jterps08 yes, I've added this error in another issue

**Comment by igaponov** [comment]
`DELETE /api/v2/stripe-accounts/{id}`

**Comment by petervojtek** [comment]
@igaponov, @jterps08 , I do not understand the workflow - when should I call `DELETE /api/v2/stripe-accounts/{id}` ?

this is how the user interface looks like:

<img width="848" alt="screen shot 2016-11-09 at 07 57 13" src="https://cloud.githubusercontent.com/assets/225506/20129731/32649f66-a652-11e6-8acd-20a951edfb00.png">

I do not think we want there additional button "Delete Stripe account" because user does not cares there is some Stripe at all, he cares only for his cards and bank accounts. Therefore I guess the `DELETE /api/v2/stripe-accounts/{id}` should be somehow invoked when Remove Account button is pressed, but what is the condition? 

And given that we have `DELETE /api/v2/stripe-accounts/{id}`, should I actually call `DELETE /api/v2/groups/{group}/bank-accounts/{id}`  ?

**Comment by jterps08** [comment]
Deleting stripe account is for deleting bank account....

not sure about removing payment card

**Comment by igaponov** [comment]
@petervojtek if user has only one bank account - call `DELETE /api/v2/stripe-accounts/{id}`, otherwise choose one and call `DELETE /api/v2/groups/{group}/bank-accounts/{id}`

**Comment by jterps08** [comment]
Groups should only have one bank account setup and one credit card setup.

Users may have multiple credit cards, but we're really only focusing on the use case of single credit card experience...

**Comment by petervojtek** [comment]
@igaponov , and how do I determine the `{id}` for `DELETE /api/v2/stripe-accounts/{id}` ?

**Comment by igaponov** [comment]
@petervojtek according to Jesse's message I'll do one account for group and change url to `/group/{id}/stripe-account`

**Comment by igaponov** [comment]
@petervojtek done

**Comment by petervojtek** [comment]
@igaponov , removing stripa account seems to fail due to:

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/332/stripe-account
Request Method:DELETE
Status Code:500 Internal Server Error

XMLHttpRequest cannot load https://api-dev.powerli.ne/api/v2/groups/332/stripe-account. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 500.
```

**Comment by igaponov** [comment]
@petervojtek @jterps08 I need to update Stripe client on backend to get method to delete an account. But after this we will need to test all functions related to Stripe.

**Comment by jterps08** [comment]
@igaponov -- What was the version we were using before? I will try to research the difference between old and new version... I'm uncertain if updating Stripe is what we want to do right now. It may break more things than not and we don't have time for that. We need to confirm that:

1) add/remove credit cards
2) add/remove bank accounts 
3) answer/pay fundraisers as group member
4) pay for subscription as group 
5) Stripe sends user payments to appropriate groups accurately
6) Stripe sends subscriptions to Powerline accurately
7) Stripe applies transaction fees to user payments accurately and sends to Powerline. 

Peter is using the Stripe.js library on the frontend. He should be completely unaffected by the upgrade on the backend.... For the backend, we need to know exactly what has changed between old client and new client...

**Comment by igaponov** [comment]
@jterps08 it's version of library, not an API. We used 2.x. I don's see major changes in 3.x.

**Comment by jterps08** [comment]
okay great that makes me feel better... thanks

**Comment by igaponov** [comment]
But still need to test all functions. Unit tests are passed.

**Comment by petervojtek** [comment]
delete stripe account works now
