### ISSUE TITLE
Disappearing Group Names in Newsfeed

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#425]
Some items have group Name (e.g. "Save the Whales") and some don't... this fixes itself after a few seconds but wondering if there's a way to address this... 

![screenshot_20161121-113938](https://cloud.githubusercontent.com/assets/7582457/20502040/5e0f4b18-b00a-11e6-8c7a-3c4c2d6537a0.png)

**Comment by petervojtek** [comment]
@jterps08 , I can reproduce this issue only in following manner:
1. I am member of some user group, and there is some content published in this group
2. I leave this group. new content no longer arrives for this group, but I still can see the old content of the left group in activity newsfeed -- and those are the items where the group name is not displayed at all.

but is it bit different bug, because the missing group name for such items will never fix (as opposed to the behaviour you describe, where the group names will actually appear after few seconds)

**Comment by jterps08** [comment]
@petervojtek ok... The issue I describe is delayed display of the group names. it is not the way you reproduced it... While I appreciate you looking at this, please do not work on anything but P1/P2 bugs or enhancements as mentioned on slack. Limited hours need to be used specifically on those items. Thanks.

**Comment by jterps08** [comment]
I believe this issue is connected to #461 ... It only appears to be a problem now on items that are appearing in the user's feed that shouldn't be there. Items that shouldn't be there are items from groups/communities the user is not a part of.
