### ISSUE TITLE
url of image in petition/post/.. text should lead to displaying this image in activity newsfeed

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#426]
originated [here](https://github.com/PowerlineApp/powerline-mobile/issues/424#issuecomment-262512073).

>  when there is a URL inside an item, metadata is leveraged to display "meta data preview" as shown below. This would not be in production.

**Comment by petervojtek** [comment]
@igaponov , when there is image URL in petition/post/poll body text, the existing frontend code expects that backend will provide for such activity item attribute `metadata`, where will be the URL of the image.

but for this userPetition we have `metadata":{"title":null,"description":null,"image":null,"url":null}` despite userPetition `description` contains an image URL:

```
{"zone":"non_prioritized","id":1055,"title":"User Petition with image url in description","description":"here is image:\nhttps://cdn.pixabay.com/photo/2015/12/09/20/09/pony-1085439_1280.png","description_html":"here is image:\nhttps://cdn.pixabay.com/photo/2015/12/09/20/09/pony-1085439_1280.png","sent_at":"2016-11-23T13:15:13.000Z","expire_at":null,"responses_count":0,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Is Leader","avatar_file_path":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg"},"user":{"official_title":"Peter10 Is Leader","full_name":"Peter10 Is Leader","id":73,"type":"user","avatar_file_name":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg"},"entity":{"type":"user-petition","id":314,"group_id":333},"picture":null,"read":false,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-11-23T13:15:13+0000","poll":null,"user_petition":{"is_subscribed":true},"post":null,"metadata":{"title":null,"description":null,"image":null,"url":null},"comments_count":1,"answers":[],"quorum":0}
```

**Comment by jterps08** [comment]
@petervojtek This is currently working to the extent that I need it to right now. I am de-prioritizing this... 

If you type in www.weather.com in a post, it displays the metadata image... <-- No change needed here

If you type in https://s3.amazonaws.com/prodpowerline/avatars/106_52ce8657a6047.jpeg in a post, it does not display any image <-- This is okay for now, but this is what this issue is truly about. My concern is that this concept would increase the risk of porn, spam, and other bad content...
