### ISSUE TITLE
Embedded YouTube videos not playing

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#436]
Not sure if this is related to https://github.com/PowerlineApp/powerline-mobile/issues/430

but this is what I get when I attach a video and try to view it either in More tab or in Newsfeed: 

![screenshot_20161130-131641](https://cloud.githubusercontent.com/assets/7582457/20765261/938d8e0c-b6ff-11e6-848e-552b55910935.png)

Two different video links I tried... 

Also: Question: What is the level of effort so that we can "preview" youtube when link is added into item's body (like a URL)?

**Comment by petervojtek** [comment]
it is fixed. the issue was that that youtube video can be provided in two different urls:
```
https://www.youtube.com/watch?v=iOmgD_aCSPM
vs
https://youtu.be/iOmgD_aCSPM
```

you used the second one, while the legacy code supported only the first one.
I fixed it so that now it works with both urls.

and the image preview is now displayed properly.

there is one annoying issue that the video box shows "Full screen is unavailable" msg, but I think that is P3 or P4 issue so I wont deal with it now.

<img width="401" alt="screenshot 2016-12-01 08 48 30" src="https://cloud.githubusercontent.com/assets/225506/20785919/1779c7e6-b7a3-11e6-8bf8-320afc307199.png">
