### ISSUE TITLE
Newsfeed Refresh after New Content Creation

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#437]
Newsfeed should be refreshed after a user has successfully created new content (post, user petition, poll, fundraiser, etc etc). Currently user needs to manually pull-to-refresh in order to refresh newsfeed and it isn't clear if the user's item was published without the refreshed newsfeed showing the content.

@petervojtek you can work on this if no available P1/P2 items.

**Comment by petervojtek** [comment]
@jterps08 , it is there, but to currently it works as following (due to nature of the source code):
1. you create new content
2. you are redirected to the new content detail
3. you click Back button and go to activity newsfeed
4. and now the newsfeed will automatically refresh and the new item will appear (in few seconds). 

to prevent those few seconds of waiting, it would be way better (also for performance reasons), if the activity newsfeed content will be updated "in the background" while the user is in step 2 (new content detail).. however this will require to refactor the activity newsfeed code (maybe 4 hours of work).

also -- when returning from item detail to activity newsfeed, user is always "thrown" to global newsfeed (activity items from all groups), even when user was on some tab-filtered activity newfeed prior entering item detail (and thus would expect being returned back to the group-specific activity newsfeed). this would require some refactoring..

**Comment by jterps08** [comment]
This works. Good to know. Thanks @petervojtek... We don't have the time right now to work on the re-factor that you suggest, but I do think it's a good idea. Marking it with Comeback label
