### ISSUE TITLE
Correct UI Favorite Button & List Performance

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#53]
Favorite buttons should toggle yellow/grey.

If yellow, the item appears in the Favorites list (accessed from the Main Menu). If grey, the item disappears from Favorites list. 

The Favorites list itself should show all items with Yellow star (there should be no group selector. only a back button to return to the home screen). There should be a back button from Favorites list back to Home screen. 

Reference: See #21 for background information.

**Comment by petervojtek** [comment]
@jterps08 , regarding this request:

> There should be a back button from Favorites list back to Home screen.

Are you sure you want it that way?
I personally find it confusing from UX point of view, because the only way how user can enter Favorites is via main (burger) menu in top left corner of Home screen. I would rather expect that the Favorites page will display the burger menu in top left corner as well, instead of back button.

Currently the Favorites screen displays burger menu in top left corner.

**Comment by jterps08** [comment]
Let's do it your way!

**Comment by petervojtek** [comment]
ok, so it's done :)
