### ISSUE TITLE
Home page first visit -- occasionally throws Cannot read property 'scrollTo' of null

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#91]
```
TypeError: Cannot read property 'scrollTo' of null
    at ionic.bundle.min.js:444
    at ionic.bundle.min.js:151
    at e (ionic.bundle.min.js:74)
    at ionic.bundle.min.js:76
```

it does not seem to hurt functionality..

**Comment by jterps08** [comment]
I wonder if this is related to the "Sticky Scrolling" concept. This basically allows the user to scroll down to an item, open it, and go back to the newsfeed and be in the same scroll position.

For example, user opens app, scrolls down to item 54 and opens item 54. User is looking at question template for item 54. user taps back button to go back to newsfeed. Newsfeed position is still item 54. This behavior is intentional.... It's not needed unless the user was in the newsfeed and then left the newsfeed and wanted to come back.

**Comment by petervojtek** [comment]
it seems the [scrollTop method](http://stackoverflow.com/a/33064710/4606227) was called too early.

**Comment by petervojtek** [comment]
it still happens..

**Comment by petervojtek** [comment]
ok, I made it more bulletproof, but the bug is non-deterministic so not sure it is 100% fixed.

**Comment by austinpapp** [comment]
we will just an eye on this for now and i dont want you wasting too much time on it for now.
