### ISSUE TITLE
Create new groups fails with XMLHttpRequest cannot load https://api-dev.powerli.ne/api/groups/

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#95]
http://localhost:8100/#/groups/create
fill in the form and click Send.

```
XMLHttpRequest cannot load https://api-dev.powerli.ne/api/groups/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 500.
```

**Comment by jterps08** [comment]
We may need Angel's help with this (@Shakaran). The new group registration method does not require the same information as the old group registration method.

For background information:
The old group registration actually provided the user, via e-mail, a username and password to log in to the admin dashboard to control the group.
The new group registration method does not provide a separate username and password for the group because single-sign-on has been implemented... The system knows the user is the group creator and gives him rights automatically (no separate login required).

If this is too hard to change (it should be a quick change based on new API), then I think it may make sense to simply hide this group creation option from the app at this time. Thoughts @austinpapp? I think we want to give users easy ability to create new groups in the app, even if they still need to use the web app to manage the group...

**Comment by petervojtek** [comment]
@igaponov , I tried to use the v2 API to create new group, but ended up with  `400 bad request`. I post all the [necessary data as described in API doc](https://api-dev.powerli.ne/api-doc#post--api-v2-user-groups), but receive `{"code":400,"message":"Validation Failed","errors":{"errors":["This form should not contain extra fields."],"children":{"username":[],"manager_first_name":[],"manager_last_name":[],"manager_email":[],"manager_phone":[],"official_type":[],"official_name":{"errors":["This value should not be blank."]},"official_description":[],"acronym":[],"official_address":[],"official_city":[],"official_state":[]}}}`.

Maybe the API doc is not matching the real API behaviour?

```
request:
Request URL:https://api-dev.powerli.ne/api/v2/user/groups
Request Method:POST
Status Code:400 Bad Request
Remote Address:52.5.45.80:443

request headers:
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Content-Length:348
Content-Type:application/json
Host:api-dev.powerli.ne
Origin:http://localhost:8100
Referer:http://localhost:8100/

request data:
{"manager_first_name":"Peter7",
"manager_last_name":"Peter7",
"manager_email":"peter7@test.com",
"manager_phone":"+1123",
"official_description":"Test",
"acronym":"PT1",
"official_address":"In the fields",
"official_city":"Fresno",
"official_state":"CA",
"username":"Peter7group1",
"official_type":"Non-Profit (Not Campaign)",
"official_title":"Peter7group1"}

response:
{"code":400,"message":"Validation Failed","errors":{"errors":["This form should not contain extra fields."],"children":{"username":[],"manager_first_name":[],"manager_last_name":[],"manager_email":[],"manager_phone":[],"official_type":[],"official_name":{"errors":["This value should not be blank."]},"official_description":[],"acronym":[],"official_address":[],"official_city":[],"official_state":[]}}}
```

**Comment by igaponov** [comment]
@petervojtek You send `official_title` parameter and form tell you: "This form should not contain extra fields.". You don't send `official_name` parameter and form tell you "official_name":{"errors":["This value should not be blank."]}. I've checked docs and the name of this parameter is `official_name`.

**Comment by petervojtek** [comment]
thank you Igor for help, I apologize I overlooked the `official_title` to `official_name` change. Now it works well.

@jterps08 , I would like to ask on how to present to user form fields `official_address`, `official_city` and `official_state` - should they be plain text fields, or should there be some address lookup (similar as in register via email), or maybe some dropdowns with US state names, ... ?

Currently I left these fields as plain text fields.

**Comment by jterps08** [comment]
@petervojtek - If Official_address, city, and state are not required for new group creation, then I think we can leave them blank _or_ pull in the city and state (only... not address) from the creator's user profile. Thoughts?

**Comment by petervojtek** [comment]
@jterps08 , they are [mandatory](https://api-dev.powerli.ne/api-doc#post--api-v2-user-groups)

**Comment by jterps08** [comment]
@igaponov can we change this or will it break something? I would like the only required fields to be: official name, official type, official description, manager first, manager last, manager e-mail... Do we need username now that Angel created single-sign on? If not, let's not include that. All other fields can be filled out later I think. Trying to make creation of a new group as quick as possible. 

Peter - from a UI standpoint, we only need to ask for official name, type, and description... We can silently provide manager first, last, and e-mail via the user's own profile.

**Comment by igaponov** [comment]
https://github.com/PowerlineApp/powerline-server/pull/176

**Comment by petervojtek** [comment]
ok, I have altered the Create new group form this way:

user must provide:
- Group username (mandatory)
- Group name (mandatory)
- Group desc (mandatory)
- Group type (mandatory)
- Group acronym

Manager contact info is automatically fetched from user profile.

I am actually not sure what is the difference/purpose of Group username (username) and Group name (official_title) -- maybe one of them can be removed from the form in order to make the form easier to fill in.

**Comment by austinpapp** [comment]
i brought this up before with regard to username. right now this is required as you know. @jterps08 username was used to sign into the group login. that username was tied to an email i believe? i think it may be worth some time to make sure we understand the relationship of these fields and original purpose. with our new sso, i'm pretty sure username is no longer necessary. i'm just not sure how coupled we are to it.

**Comment by jterps08** [comment]
@petervojtek - The simpler we can make the form, the better! If we can remove username, that would be nice.  

@austinpapp I think you will want to look at the Mailgun integration https://github.com/PowerlineApp/powerline-server/pull/21 (or other related PRs as there were several)... From what I recall, the Mailgun integration slugifies the official_title for the mailing list name INSTEAD of the username... 

I do not think we need username at all under the new group registration process, but I'm not sure... I think we kept the field in there for backwards compatibility and _maybe_ for URL routing (e.g. powerli.ne/s/groupusername)... Not sure. I believe this may be covered in the infamous 101 PR by Angel: https://github.com/PowerlineApp/powerline-server/pull/101

**Comment by austinpapp** [comment]
i'll need to review username a bit more. again, just not sure how coupled we are to it as it was part of the original codebase (used to actually log in to admin the group). however, anything that gets slugified should be the official title (name of the group) and not the username. 

i'll look more into it.

**Comment by austinpapp** [comment]
PowerlineApp/powerline-server#176 was deployed.

**Comment by jterps08** [comment]
Is this closed now because 176 is deployed?

**Comment by petervojtek** [comment]
I can create new groups now, so from mobile app point of view this seems to be fixed.
